"""perf indexes

Revision ID: 11e1cc89ae3a
Revises: 7bab2b9ff482
Create Date: 2026-08-16 15:10:55.342669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e1cc89ae3a'
down_revision: Union[str, Sequence[str], None] = '7bab2b9ff482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_code_email', 'discount_redemptions', ['code_id', 'email'], unique=False)
    op.create_index('uk_code_email', 'referrals', ['code', 'invited_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_code_email', table_name='referrals')
    op.drop_index('idx_code_email', table_name='discount_redemptions')
    # ### end Alembic commands ###
