"""init 51 tables

Revision ID: 7bab2b9ff482
Revises: 
Create Date: 2026-08-15 23:12:13.716342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bab2b9ff482'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('diff_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_created', 'admin_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_entity', 'admin_logs', ['entity', 'entity_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cover', sa.String(length=500), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bundles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('variant_ids', sa.JSON(), nullable=False),
    sa.Column('bundle_price', sa.Integer(), nullable=False),
    sa.Column('active', sa.SmallInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('abandoned_mails_sent', sa.SmallInteger(), nullable=False),
    sa.Column('recovery_token', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_carts_updated_at'), 'carts', ['updated_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('collection_products',
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('collection_id', 'product_id')
    )
    op.create_index(op.f('ix_collection_products_product_id'), 'collection_products', ['product_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('rule_json', sa.JSON(), nullable=False),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cookie_consents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('necessary', sa.SmallInteger(), nullable=False),
    sa.Column('analytics', sa.SmallInteger(), nullable=False),
    sa.Column('marketing', sa.SmallInteger(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookie_consents_session_id'), 'cookie_consents', ['session_id'], unique=False)
    op.create_table('data_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_subtotal', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('max_discount', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('first_order_only', sa.SmallInteger(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_stacked', sa.SmallInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_active_window', 'discount_codes', ['is_active', 'starts_at', 'ends_at'], unique=False)
    op.create_table('discount_redemptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_redemptions_code_id'), 'discount_redemptions', ['code_id'], unique=False)
    op.create_table('email_preferences',
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('sub_promo', sa.SmallInteger(), nullable=False),
    sa.Column('sub_new_arrival', sa.SmallInteger(), nullable=False),
    sa.Column('sub_cart_abandon', sa.SmallInteger(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_no', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('old_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('new_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('price_diff', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('diff_payment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_no')
    )
    op.create_index(op.f('ix_exchanges_order_id'), 'exchanges', ['order_id'], unique=False)
    op.create_table('faqs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.SmallInteger(), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_table('gift_card_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('gift_card_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('change_type', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_card_ledger_gift_card_id'), 'gift_card_ledger', ['gift_card_id'], unique=False)
    op.create_table('gift_cards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=19), nullable=False),
    sa.Column('initial_amount', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('purchaser_email', sa.String(length=191), nullable=False),
    sa.Column('purchaser_order_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_email', sa.String(length=191), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_gift_cards_status'), 'gift_cards', ['status'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('klaviyo_synced', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('product_slug', sa.String(length=150), nullable=False),
    sa.Column('title_snapshot', sa.String(length=300), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('refunded_qty', sa.Integer(), nullable=False),
    sa.Column('exchanged_qty', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.create_table('order_timeline',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_created', 'order_timeline', ['order_id', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('shipping_status', sa.SmallInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('discount_total', sa.Integer(), nullable=False),
    sa.Column('points_discount', sa.Integer(), nullable=False),
    sa.Column('giftcard_discount', sa.Integer(), nullable=False),
    sa.Column('shipping_fee', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('discount_code_id', sa.BigInteger(), nullable=True),
    sa.Column('points_used', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('gift_flag', sa.SmallInteger(), nullable=False),
    sa.Column('gift_message', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('utm_json', sa.JSON(), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('tracking_no', sa.String(length=64), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_status_placed', 'orders', ['status', 'placed_at'], unique=False)
    op.create_index('idx_user_placed', 'orders', ['user_id', 'placed_at'], unique=False)
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_source'), 'orders', ['source'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=30), nullable=False),
    sa.Column('aggregate_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('published', sa.SmallInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unpublished', 'outbox_events', ['published', 'created_at'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('provider_ref', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_order_id'), 'payment_methods', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_provider_ref'), 'payment_methods', ['provider_ref'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('stripe_payment_intent', sa.String(length=64), nullable=True),
    sa.Column('stripe_checkout_session', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('refunded_amount', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent'), 'payments', ['stripe_payment_intent'], unique=False)
    op.create_table('points_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.SmallInteger(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('frozen', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expires', 'points_ledger', ['expires_at'], unique=False)
    op.create_index('idx_user_created', 'points_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('popup_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scene', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('coupon_code', sa.String(length=32), nullable=True),
    sa.Column('trigger_rules', sa.JSON(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.SmallInteger(), nullable=False),
    sa.Column('stats_shown', sa.Integer(), nullable=False),
    sa.Column('stats_converted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popup_configs_scene'), 'popup_configs', ['scene'], unique=False)
    op.create_table('product_translations',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description_md', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('product_id', 'locale')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description_md', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('compare_at_price', sa.Integer(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=False),
    sa.Column('price_max', sa.Integer(), nullable=False),
    sa.Column('hero_image', sa.String(length=500), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_new', sa.SmallInteger(), nullable=False),
    sa.Column('is_best_seller', sa.SmallInteger(), nullable=False),
    sa.Column('rating_avg', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_best', 'products', ['is_best_seller', 'status'], unique=False)
    op.create_index('idx_cat_status_pub', 'products', ['category_id', 'status', 'published_at'], unique=False)
    op.create_index('idx_new', 'products', ['is_new', 'status', 'published_at'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_po_id'), 'purchase_order_items', ['po_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('po_no', sa.String(length=14), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('expected_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_no')
    )
    op.create_table('reconciliation_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reconcile_date', sa.Date(), nullable=False),
    sa.Column('stripe_gross', sa.Integer(), nullable=True),
    sa.Column('stripe_fee', sa.Integer(), nullable=True),
    sa.Column('payments_gross', sa.Integer(), nullable=True),
    sa.Column('orders_paid_total', sa.Integer(), nullable=True),
    sa.Column('diff_payment', sa.Integer(), nullable=False),
    sa.Column('diff_refund', sa.Integer(), nullable=False),
    sa.Column('points_ledger_sum', sa.Integer(), nullable=True),
    sa.Column('users_points_sum', sa.Integer(), nullable=True),
    sa.Column('diff_points', sa.Integer(), nullable=False),
    sa.Column('stock_diff_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconcile_date')
    )
    op.create_table('referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_email', sa.String(length=191), nullable=False),
    sa.Column('invited_user_id', sa.BigInteger(), nullable=True),
    sa.Column('first_order_no', sa.String(length=20), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('reward_referrer', sa.Integer(), nullable=False),
    sa.Column('reward_invitee', sa.Integer(), nullable=False),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_table('reply_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rma_no', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.SmallInteger(), nullable=False),
    sa.Column('reason_detail', sa.String(length=500), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('label_url', sa.String(length=500), nullable=True),
    sa.Column('label_cost', sa.Integer(), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=True),
    sa.Column('refund_shipping', sa.Integer(), nullable=False),
    sa.Column('restock_qty', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rma_no')
    )
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_returns_reason'), 'returns', ['reason'], unique=False)
    op.create_index(op.f('ix_returns_status'), 'returns', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('reject_reason', sa.String(length=100), nullable=True),
    sa.Column('edited_after_reject', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_index('idx_product_status', 'reviews', ['product_id', 'status', 'created_at'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_no', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('carrier', sa.String(length=30), nullable=False),
    sa.Column('tracking_no', sa.String(length=64), nullable=False),
    sa.Column('label_url', sa.String(length=500), nullable=True),
    sa.Column('label_cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('item_json', sa.JSON(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_no')
    )
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_no'), 'shipments', ['tracking_no'], unique=False)
    op.create_table('shipping_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dest_country', sa.String(length=2), nullable=False),
    sa.Column('carrier', sa.String(length=30), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('min_weight_g', sa.Integer(), nullable=False),
    sa.Column('max_weight_g', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('free_over', sa.Integer(), nullable=True),
    sa.Column('eta_min_days', sa.SmallInteger(), nullable=False),
    sa.Column('eta_max_days', sa.SmallInteger(), nullable=False),
    sa.Column('active', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rates_dest_country'), 'shipping_rates', ['dest_country'], unique=False)
    op.create_table('stock_counts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=False),
    sa.Column('diff', sa.Integer(), nullable=False),
    sa.Column('counted_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_counts_variant_id'), 'stock_counts', ['variant_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('operator', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type_time', 'stock_movements', ['type', 'created_at'], unique=False)
    op.create_index('idx_variant_time', 'stock_movements', ['variant_id', 'created_at'], unique=False)
    op.create_table('stock_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('converted_order_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.SmallInteger(), nullable=False),
    sa.Column('style_mode', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('next_billing_at', sa.DateTime(), nullable=False),
    sa.Column('resume_at', sa.DateTime(), nullable=True),
    sa.Column('skip_until', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_next_billing_at'), 'subscriptions', ['next_billing_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('lead_time_days', sa.SmallInteger(), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('sender', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=14), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('order_no', sa.String(length=20), nullable=True),
    sa.Column('category', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('assignee_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('first_reply_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.SmallInteger(), nullable=True),
    sa.Column('satisfaction', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_index('idx_assignee', 'tickets', ['assignee_admin_id', 'status'], unique=False)
    op.create_index('idx_status_priority', 'tickets', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('ugc_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('related_product_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('points_rewarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('line1', sa.String(length=191), nullable=False),
    sa.Column('line2', sa.String(length=191), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_default', sa.SmallInteger(), nullable=False),
    sa.Column('verified', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('tier_updated_at', sa.DateTime(), nullable=True),
    sa.Column('risk_flag', sa.SmallInteger(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_order_at'), 'users', ['last_order_at'], unique=False)
    op.create_table('variant_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_images_variant_id'), 'variant_images', ['variant_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('option1_name', sa.String(length=50), nullable=False),
    sa.Column('option1_value', sa.String(length=50), nullable=False),
    sa.Column('option2_name', sa.String(length=50), nullable=False),
    sa.Column('option2_value', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('weight_gram', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('wishlist_items',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_items')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_variant_images_variant_id'), table_name='variant_images')
    op.drop_table('variant_images')
    op.drop_index(op.f('ix_users_last_order_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_table('ugc_submissions')
    op.drop_index('idx_status_priority', table_name='tickets')
    op.drop_index('idx_assignee', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_billing_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('stock_notifications')
    op.drop_index('idx_variant_time', table_name='stock_movements')
    op.drop_index('idx_type_time', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_counts_variant_id'), table_name='stock_counts')
    op.drop_table('stock_counts')
    op.drop_index(op.f('ix_shipping_rates_dest_country'), table_name='shipping_rates')
    op.drop_table('shipping_rates')
    op.drop_index(op.f('ix_shipments_tracking_no'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('settings')
    op.drop_index('idx_product_status', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_returns_status'), table_name='returns')
    op.drop_index(op.f('ix_returns_reason'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_table('reply_templates')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('reconciliation_daily')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_purchase_order_items_po_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('idx_new', table_name='products')
    op.drop_index('idx_cat_status_pub', table_name='products')
    op.drop_index('idx_best', table_name='products')
    op.drop_table('products')
    op.drop_table('product_translations')
    op.drop_index(op.f('ix_popup_configs_scene'), table_name='popup_configs')
    op.drop_table('popup_configs')
    op.drop_index('idx_user_created', table_name='points_ledger')
    op.drop_index('idx_expires', table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index(op.f('ix_payments_stripe_payment_intent'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_methods_provider_ref'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_order_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index('idx_unpublished', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_orders_source'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_index('idx_user_placed', table_name='orders')
    op.drop_index('idx_status_placed', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_order_created', table_name='order_timeline')
    op.drop_table('order_timeline')
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_gift_cards_status'), table_name='gift_cards')
    op.drop_table('gift_cards')
    op.drop_index(op.f('ix_gift_card_ledger_gift_card_id'), table_name='gift_card_ledger')
    op.drop_table('gift_card_ledger')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_exchanges_order_id'), table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_table('email_preferences')
    op.drop_index(op.f('ix_discount_redemptions_code_id'), table_name='discount_redemptions')
    op.drop_table('discount_redemptions')
    op.drop_index('idx_active_window', table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_cookie_consents_session_id'), table_name='cookie_consents')
    op.drop_table('cookie_consents')
    op.drop_table('collections')
    op.drop_index(op.f('ix_collection_products_product_id'), table_name='collection_products')
    op.drop_table('collection_products')
    op.drop_table('categories')
    op.drop_index(op.f('ix_carts_updated_at'), table_name='carts')
    op.drop_table('carts')
    op.drop_table('bundles')
    op.drop_table('articles')
    op.drop_index('idx_entity', table_name='admin_logs')
    op.drop_index('idx_admin_created', table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
